name: npm-publish

# on 关键字的使用文档
# https://help.github.com/en/articles/workflow-syntax-for-github-actions#onevent_nametypes
on:
  push:
    branches:
      - master

jobs:
  npm-publish:
    strategy:
      matrix:
        node-version: [10]
        os: [macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}
      - run: echo "machine github.com login chenhaihong password ${{ secrets.GH_TOKEN }}" > ~/.netrc
      # 登录npm https://www.npmjs.com/package/npm-cli-login
      - run: npm i -g npm-cli-login
      # secrets值的地址 https://github.com/chenhaihong/vaf/settings/secrets/actions
      - run: NPM_USER=erye NPM_PASS=${{ matrix.NPM_PASS }} NPM_EMAIL=erye@tiiit.cn npm-cli-login
      - run: npm run pub
